name: Keep draw.io export synchronized
on:
  push:
    branches:
      - main
    paths:
      - "**.drawio"
      - .github/workflows/drawio-export.yml
concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Export drawio files to .pdf
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: pdf
      - name: Export drawio files to. md
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: md
      - name: Export drawio files to .jpg
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: jpg
          quality: 100
      - name: Export drawio files to .png
        uses: rlespinasse/drawio-export-action@v2
        with:
          format:
          transparent: true
      - name: Export drawio files to .svg
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: svg
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn rename
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "me@shu.nu"
          git config --global user.name "shun-ueda"
          git add -A
          git commit -m "[Actions] Sync diagram" || exit 0
          git push